---
- name: Install MariaDB server and required Python MySQL library
  ansible.builtin.yum:
    name:
      - mariadb-server
      - python3-PyMySQL
    state: present

- name: Ensure MariaDB is running and enabled
  ansible.builtin.service:
    name: mariadb
    state: started
    enabled: yes

- name: Create application database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/lib/mysql/mysql.sock

- name: Create application DB user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_user: root
    login_unix_socket: /var/lib/mysql/mysql.sock
